# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/budgeter.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/budgeter.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x01\n\x0bTransaction\x12(\n\x04\x64\x61te\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x65nvelope\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x63\x63ount\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\r\n\x05notes\x18\x05 \x01(\t\x12\x0e\n\x06\x61mount\x18\x06 \x01(\x02\x12\x0f\n\x07\x64\x65tails\x18\x07 \x01(\t\"?\n\x19RecordTransactionsRequest\x12\"\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x0c.Transaction\"5\n\x17RecordTransactionsReply\x12\x1a\n\x12transactions_count\x18\x01 \x01(\x05\x32X\n\x08\x42udgeter\x12L\n\x12RecordTransactions\x12\x1a.RecordTransactionsRequest\x1a\x18.RecordTransactionsReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.budgeter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=59
  _globals['_TRANSACTION']._serialized_end=211
  _globals['_RECORDTRANSACTIONSREQUEST']._serialized_start=213
  _globals['_RECORDTRANSACTIONSREQUEST']._serialized_end=276
  _globals['_RECORDTRANSACTIONSREPLY']._serialized_start=278
  _globals['_RECORDTRANSACTIONSREPLY']._serialized_end=331
  _globals['_BUDGETER']._serialized_start=333
  _globals['_BUDGETER']._serialized_end=421
# @@protoc_insertion_point(module_scope)
